arch: 'SNGAN'

path: '/path/to/your/input/images/'
out: '/path/to/your/output/images/'
run: 'SNGAN_256x256'
seed: 42
n_gpu: 1  # Adjust based on your GPU availability

num_epochs: 500  # Increased epochs for larger image size
learning_rate: 0.0002
beta_adam: 0.5
batch_size: 16  # Smaller batch size for larger images

latent_vector: 256

image_size: 256  # Set to 256 for your architecture
loader_workers: 2
number_channels: 3
gen_feature_maps: 64
dis_feature_maps: 64

# Spectral Normalization is applied to the discriminator
use_spectral_norm: true

# Learning rate adjustment
generator_lr: 0.0002
discriminator_lr: 0.002  # 10x the generator learning rate

# Label smoothing
use_label_smoothing: true
smooth_label: 0.9