arch: 'SNGAN'
path: '/kaggle/input/skin-lesion/images'
out: '/kaggle/working/ganoutput'
run: 'SNGAN_256x256'
seed: 42
n_gpu: 1
num_epochs: 500
learning_rate: 0.0002
beta_adam: 0.5
batch_size: 16
latent_vector: 256
image_size: 256
loader_workers: 2
number_channels: 3
gen_feature_maps: 64
dis_feature_maps: 64
use_spectral_norm: true
generator_lr: 0.0002
discriminator_lr: 0.002
use_label_smoothing: true
smooth_label: 0.9